server:
  port: 9091


eureka:
  client:
  service-url:
    defaultZone: 'http://localhost:8761/eureka/'

spring:
  profiles:
    active: local

  application:
    name: RESTAURANT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantdb
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect